page_title: Bogdan David - Nova Card
description: bogdandavid Nova Card profile
baseurl: /
url: https://template-01.novacard.ro
avatar: avatar.jpeg
contact-first_name: Bogdan
contact-last_name: David
contact-title: Director
contact-company: BDmetal
contact-email: 
contact-phone: +40756367342
contact-website: http://bdmetal.ro/
contact-facebook_url: https://www.facebook.com/bdmetalro-109115840924488
contact-linkedin_url: 
contact-instagram_url: 
contact-pinterest_url: 
contact-twitter_url: 
contact-youtube_url: 
contact-snapchat_url: 
contact-whatsapp_url: 
contact-tiktok_url: 
contact-telegram_url: 
contact-skype_url: 
contact-github_url: 
contact-gitlab_url: 
markdown: kramdown
